### PR TITLE
Design the tasks page#1

### PR DESCRIPTION
**Pull request by Min1600**
Hi, please have a look at the code, I added a tasks.css file in the css folder that is linked to the tasks.html file. Thank you.

### CODE REVIEW

**Review by TzivyaFireman — COMMENTED** [review]
Everything is working great. I just want the background to change to green, like the example you showed me. Also, I want the employee management button to not appear at all if the user is not a manager. Other than that, everything is perfect!

**Comment by TzivyaFireman** [comment]
The page looks almost perfect! I have a request for a few small changes:
- Change the text to User Details.
- Reduce the size of the user icon along with the text, and ensure that clicking on the icon also leads to the users' page.
- If the username is not displayed, it would be better to remove the word USERNAME.
I hope there won’t be any further requests. Thank you!

**Comment by TzivyaFireman** [comment]
Hey,
I haven't thoroughly reviewed the code, but I ran it on my end, 
and the link to the users' page is not appearing at all right now.

**Comment by Min1600** [comment]
Hi,
was it working before the most recent pull request? 
I think it has something to do with the tasks.js file where it authenticates if you are admin or not? I did not change that part of the code.

**Comment by TzivyaFireman** [comment]
I understand the issue. The button isn’t showing because it’s wrapped in a hidden <a> tag.
Just move the display: none from the <a> to the button itself.
like that: 
image
If you can’t see the button because you’re not logged in as an admin, use the username and password: aaa, aaa.

**Comment by Min1600** [comment]
> I understand the issue. The button isn’t showing because it’s wrapped in a hidden tag. Just move the display: none from the to the button itself. like that: image In addition, please adjust the design to make it cleaner, If you can’t see the button because you’re not logged in as an admin, use the username and password: aaa, aaa.

Oh, my mistake I should have put display: none onto button, I am not sure what you meant by cleaner is there a specific part of the design that you want to be changed?

**Review by TzivyaFireman — APPROVED** [review]
Thank you for your excellent work.
I highly appreciate the effort and dedication you put into completing the task. Everything looks great, and I am approving the PR.

**Pull request merged**
